=begin
#Vehicle Maintance Manager

#This is a sample vehicle maintance manager server.

OpenAPI spec version: 0.0.1
Contact: apiteam@vmmapi
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::Vehicle
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Vehicle' do
  before do
    # run before each test
    @instance = SwaggerClient::Vehicle.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Vehicle' do
    it 'should create an instance of Vehicle' do
      expect(@instance).to be_instance_of(SwaggerClient::Vehicle)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "user_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "photo_urls"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "vehicle_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["motorcycle", "automobile", "tank"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.vehicle_type = value }.not_to raise_error
       #end
    end
  end

end

