/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator 2.2.3.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * GarageApi.h
 *
 * 
 */

#ifndef GarageApi_H_
#define GarageApi_H_


#include "ApiClient.h"


namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  GarageApi
{
public:
    GarageApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~GarageApi();
    /// <summary>
    /// Get all registered vehicles
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    
    pplx::task<void> garageInventoryGet();

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* GarageApi_H_ */

