/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator 2.2.3.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ReminderApi.h
 *
 * 
 */

#ifndef ReminderApi_H_
#define ReminderApi_H_


#include "ApiClient.h"

#include "Reminder.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  ReminderApi
{
public:
    ReminderApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~ReminderApi();
    /// <summary>
    /// Add a reminder to the vehicle
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="vehicleId">ID of vehicle that needs to be updated</param>/// <param name="message">Reminder message</param>
    pplx::task<void> addReminderToVehicleId(int64_t vehicleId, utility::string_t message);
    /// <summary>
    /// Deletes a reminder
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="reminderId">reminder id to delete</param>/// <param name="apiKey"> (optional)</param>
    pplx::task<void> deleteReminder(int64_t reminderId, utility::string_t apiKey);
    /// <summary>
    /// Find reminder by ID
    /// </summary>
    /// <remarks>
    /// Returns a single reminder
    /// </remarks>
    /// <param name="reminderId">ID of reminder to return</param>
    pplx::task<std::shared_ptr<Reminder>> getReminderById(int64_t reminderId);

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ReminderApi_H_ */

