/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator 2.2.3.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * TripApi.h
 *
 * 
 */

#ifndef TripApi_H_
#define TripApi_H_


#include "ApiClient.h"

#include "Trip.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  TripApi
{
public:
    TripApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~TripApi();
    /// <summary>
    /// Add a trip log to the vehicle
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="vehicleId">ID of vehicle that needs to be updated</param>/// <param name="quantity">Fuel Quantity</param>
    pplx::task<void> addTripToVehicleId(int64_t vehicleId, double quantity);
    /// <summary>
    /// Deletes a trip log
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="tripId">trip id to delete</param>/// <param name="apiKey"> (optional)</param>
    pplx::task<void> deleteTrip(int64_t tripId, utility::string_t apiKey);
    /// <summary>
    /// Find trip by ID
    /// </summary>
    /// <remarks>
    /// Returns a single trip log
    /// </remarks>
    /// <param name="tripId">ID of trip to return</param>
    pplx::task<std::shared_ptr<Trip>> getTripById(int64_t tripId);

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* TripApi_H_ */

