/*
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.math.BigDecimal;
import io.swagger.client.model.Fine;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FineApi
 */
@Ignore
public class FineApiTest {

    private final FineApi api = new FineApi();

    
    /**
     * Add a fine to the vehicle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addFineToVehicleIdTest() throws ApiException {
        Long vehicleId = null;
        BigDecimal amount = null;
        api.addFineToVehicleId(vehicleId, amount);

        // TODO: test validations
    }
    
    /**
     * Deletes a fine
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFineTest() throws ApiException {
        Long fineId = null;
        String apiKey = null;
        api.deleteFine(fineId, apiKey);

        // TODO: test validations
    }
    
    /**
     * Find fine by ID
     *
     * Returns a single fine
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFineByIdTest() throws ApiException {
        Long fineId = null;
        Fine response = api.getFineById(fineId);

        // TODO: test validations
    }
    
}
