/*
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GarageApi
 */
@Ignore
public class GarageApiTest {

    private final GarageApi api = new GarageApi();

    
    /**
     * Get all registered vehicles
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void garageInventoryGetTest() throws ApiException {
        api.garageInventoryGet();

        // TODO: test validations
    }
    
}
