/*
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Reminder;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReminderApi
 */
@Ignore
public class ReminderApiTest {

    private final ReminderApi api = new ReminderApi();

    
    /**
     * Add a reminder to the vehicle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addReminderToVehicleIdTest() throws ApiException {
        Long vehicleId = null;
        String message = null;
        api.addReminderToVehicleId(vehicleId, message);

        // TODO: test validations
    }
    
    /**
     * Deletes a reminder
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteReminderTest() throws ApiException {
        Long reminderId = null;
        String apiKey = null;
        api.deleteReminder(reminderId, apiKey);

        // TODO: test validations
    }
    
    /**
     * Find reminder by ID
     *
     * Returns a single reminder
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReminderByIdTest() throws ApiException {
        Long reminderId = null;
        Reminder response = api.getReminderById(reminderId);

        // TODO: test validations
    }
    
}
