/*
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.math.BigDecimal;
import io.swagger.client.model.Trip;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TripApi
 */
@Ignore
public class TripApiTest {

    private final TripApi api = new TripApi();

    
    /**
     * Add a trip log to the vehicle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTripToVehicleIdTest() throws ApiException {
        Long vehicleId = null;
        BigDecimal quantity = null;
        api.addTripToVehicleId(vehicleId, quantity);

        // TODO: test validations
    }
    
    /**
     * Deletes a trip log
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTripTest() throws ApiException {
        Long tripId = null;
        String apiKey = null;
        api.deleteTrip(tripId, apiKey);

        // TODO: test validations
    }
    
    /**
     * Find trip by ID
     *
     * Returns a single trip log
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTripByIdTest() throws ApiException {
        Long tripId = null;
        Trip response = api.getTripById(tripId);

        // TODO: test validations
    }
    
}
