/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.VehicleMaintanceManager) {
      root.VehicleMaintanceManager = {};
    }
    root.VehicleMaintanceManager.Vehicle = factory(root.VehicleMaintanceManager.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Vehicle model module.
   * @module model/Vehicle
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Vehicle</code>.
   * @alias module:model/Vehicle
   * @class
   * @param name {String} 
   * @param photoUrls {Array.<String>} 
   * @param vehicleType {module:model/Vehicle.VehicleTypeEnum} Type of vehicle
   */
  var exports = function(name, photoUrls, vehicleType) {
    var _this = this;



    _this['name'] = name;
    _this['photoUrls'] = photoUrls;
    _this['vehicleType'] = vehicleType;
  };

  /**
   * Constructs a <code>Vehicle</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Vehicle} obj Optional instance to populate.
   * @return {module:model/Vehicle} The populated <code>Vehicle</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('photoUrls')) {
        obj['photoUrls'] = ApiClient.convertToType(data['photoUrls'], ['String']);
      }
      if (data.hasOwnProperty('vehicleType')) {
        obj['vehicleType'] = ApiClient.convertToType(data['vehicleType'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Array.<String>} photoUrls
   */
  exports.prototype['photoUrls'] = undefined;
  /**
   * Type of vehicle
   * @member {module:model/Vehicle.VehicleTypeEnum} vehicleType
   */
  exports.prototype['vehicleType'] = undefined;


  /**
   * Allowed values for the <code>vehicleType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.VehicleTypeEnum = {
    /**
     * value: "motorcycle"
     * @const
     */
    "motorcycle": "motorcycle",
    /**
     * value: "automobile"
     * @const
     */
    "automobile": "automobile",
    /**
     * value: "tank"
     * @const
     */
    "tank": "tank"  };


  return exports;
}));


