/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator 2.2.3.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "Fine.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

Fine::Fine()
{
    m_Id = 0L;
    m_IdIsSet = false;
    m_VehicleId = 0L;
    m_Name = U("");
    m_Description = U("");
}

Fine::~Fine()
{
}

void Fine::validate()
{
    // TODO: implement validation
}

web::json::value Fine::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_IdIsSet)
    {
        val[U("id")] = ModelBase::toJson(m_Id);
    }
    val[U("vehicleId")] = ModelBase::toJson(m_VehicleId);
    val[U("name")] = ModelBase::toJson(m_Name);
    val[U("description")] = ModelBase::toJson(m_Description);

    return val;
}

void Fine::fromJson(web::json::value& val)
{
    if(val.has_field(U("id")))
    {
        setId(ModelBase::int64_tFromJson(val[U("id")]));
    }
    setVehicleId(ModelBase::int64_tFromJson(val[U("vehicleId")]));
    setName(ModelBase::stringFromJson(val[U("name")]));
    setDescription(ModelBase::stringFromJson(val[U("description")]));
}

void Fine::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("id"), m_Id));
    }
    multipart->add(ModelBase::toHttpContent(namePrefix + U("vehicleId"), m_VehicleId));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("name"), m_Name));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("description"), m_Description));
}

void Fine::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("id")))
    {
        setId(ModelBase::int64_tFromHttpContent(multipart->getContent(U("id"))));
    }
    setVehicleId(ModelBase::int64_tFromHttpContent(multipart->getContent(U("vehicleId"))));
    setName(ModelBase::stringFromHttpContent(multipart->getContent(U("name"))));
    setDescription(ModelBase::stringFromHttpContent(multipart->getContent(U("description"))));
}

int64_t Fine::getId() const
{
    return m_Id;
}


void Fine::setId(int64_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool Fine::idIsSet() const
{
    return m_IdIsSet;
}

void Fine::unsetId()
{
    m_IdIsSet = false;
}

int64_t Fine::getVehicleId() const
{
    return m_VehicleId;
}


void Fine::setVehicleId(int64_t value)
{
    m_VehicleId = value;
    
}
utility::string_t Fine::getName() const
{
    return m_Name;
}


void Fine::setName(utility::string_t value)
{
    m_Name = value;
    
}
utility::string_t Fine::getDescription() const
{
    return m_Description;
}


void Fine::setDescription(utility::string_t value)
{
    m_Description = value;
    
}
}
}
}
}

