/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator 2.2.3.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "Garage.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

Garage::Garage()
{
    m_Id = 0L;
    m_IdIsSet = false;
    m_UserId = 0L;
    m_UserIdIsSet = false;
    m_Name = U("");
}

Garage::~Garage()
{
}

void Garage::validate()
{
    // TODO: implement validation
}

web::json::value Garage::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_IdIsSet)
    {
        val[U("id")] = ModelBase::toJson(m_Id);
    }
    if(m_UserIdIsSet)
    {
        val[U("userId")] = ModelBase::toJson(m_UserId);
    }
    val[U("name")] = ModelBase::toJson(m_Name);

    return val;
}

void Garage::fromJson(web::json::value& val)
{
    if(val.has_field(U("id")))
    {
        setId(ModelBase::int64_tFromJson(val[U("id")]));
    }
    if(val.has_field(U("userId")))
    {
        setUserId(ModelBase::int64_tFromJson(val[U("userId")]));
    }
    setName(ModelBase::stringFromJson(val[U("name")]));
}

void Garage::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("id"), m_Id));
    }
    if(m_UserIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("userId"), m_UserId));
    }
    multipart->add(ModelBase::toHttpContent(namePrefix + U("name"), m_Name));
}

void Garage::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("id")))
    {
        setId(ModelBase::int64_tFromHttpContent(multipart->getContent(U("id"))));
    }
    if(multipart->hasContent(U("userId")))
    {
        setUserId(ModelBase::int64_tFromHttpContent(multipart->getContent(U("userId"))));
    }
    setName(ModelBase::stringFromHttpContent(multipart->getContent(U("name"))));
}

int64_t Garage::getId() const
{
    return m_Id;
}


void Garage::setId(int64_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool Garage::idIsSet() const
{
    return m_IdIsSet;
}

void Garage::unsetId()
{
    m_IdIsSet = false;
}

int64_t Garage::getUserId() const
{
    return m_UserId;
}


void Garage::setUserId(int64_t value)
{
    m_UserId = value;
    m_UserIdIsSet = true;
}
bool Garage::userIdIsSet() const
{
    return m_UserIdIsSet;
}

void Garage::unsetUserId()
{
    m_UserIdIsSet = false;
}

utility::string_t Garage::getName() const
{
    return m_Name;
}


void Garage::setName(utility::string_t value)
{
    m_Name = value;
    
}
}
}
}
}

