/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator 2.2.3.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Refuel.h
 *
 * 
 */

#ifndef Refuel_H_
#define Refuel_H_


#include "ModelBase.h"


namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Refuel
    : public ModelBase
{
public:
    Refuel();
    virtual ~Refuel();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Refuel members

    /// <summary>
    /// 
    /// </summary>
    int64_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int64_t value);
    /// <summary>
    /// 
    /// </summary>
    int64_t getVehicleId() const;
        void setVehicleId(int64_t value);
    /// <summary>
    /// 
    /// </summary>
    int64_t getQuantity() const;
        void setQuantity(int64_t value);

protected:
    int64_t m_Id;
    bool m_IdIsSet;
    int64_t m_VehicleId;
        int64_t m_Quantity;
    };

}
}
}
}

#endif /* Refuel_H_ */
