/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator 2.2.3.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "Vehicle.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

Vehicle::Vehicle()
{
    m_Id = 0L;
    m_IdIsSet = false;
    m_UserId = 0L;
    m_UserIdIsSet = false;
    m_Name = U("");
    m_VehicleType = U("");
}

Vehicle::~Vehicle()
{
}

void Vehicle::validate()
{
    // TODO: implement validation
}

web::json::value Vehicle::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_IdIsSet)
    {
        val[U("id")] = ModelBase::toJson(m_Id);
    }
    if(m_UserIdIsSet)
    {
        val[U("userId")] = ModelBase::toJson(m_UserId);
    }
    val[U("name")] = ModelBase::toJson(m_Name);
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_PhotoUrls )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        val[U("photoUrls")] = web::json::value::array(jsonArray);
    }
    val[U("vehicleType")] = ModelBase::toJson(m_VehicleType);

    return val;
}

void Vehicle::fromJson(web::json::value& val)
{
    if(val.has_field(U("id")))
    {
        setId(ModelBase::int64_tFromJson(val[U("id")]));
    }
    if(val.has_field(U("userId")))
    {
        setUserId(ModelBase::int64_tFromJson(val[U("userId")]));
    }
    setName(ModelBase::stringFromJson(val[U("name")]));
    {
        m_PhotoUrls.clear();
        std::vector<web::json::value> jsonArray;
        for( auto& item : val[U("photoUrls")].as_array() )
        {
            m_PhotoUrls.push_back(ModelBase::stringFromJson(item));
        }
    }
    setVehicleType(ModelBase::stringFromJson(val[U("vehicleType")]));
}

void Vehicle::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("id"), m_Id));
    }
    if(m_UserIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("userId"), m_UserId));
    }
    multipart->add(ModelBase::toHttpContent(namePrefix + U("name"), m_Name));
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_PhotoUrls )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        multipart->add(ModelBase::toHttpContent(namePrefix + U("photoUrls"), web::json::value::array(jsonArray), U("application/json")));
            }
    multipart->add(ModelBase::toHttpContent(namePrefix + U("vehicleType"), m_VehicleType));
}

void Vehicle::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("id")))
    {
        setId(ModelBase::int64_tFromHttpContent(multipart->getContent(U("id"))));
    }
    if(multipart->hasContent(U("userId")))
    {
        setUserId(ModelBase::int64_tFromHttpContent(multipart->getContent(U("userId"))));
    }
    setName(ModelBase::stringFromHttpContent(multipart->getContent(U("name"))));
    {
        m_PhotoUrls.clear();

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("photoUrls"))));
        for( auto& item : jsonArray.as_array() )
        {
            m_PhotoUrls.push_back(ModelBase::stringFromJson(item));
        }
    }
    setVehicleType(ModelBase::stringFromHttpContent(multipart->getContent(U("vehicleType"))));
}

int64_t Vehicle::getId() const
{
    return m_Id;
}


void Vehicle::setId(int64_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool Vehicle::idIsSet() const
{
    return m_IdIsSet;
}

void Vehicle::unsetId()
{
    m_IdIsSet = false;
}

int64_t Vehicle::getUserId() const
{
    return m_UserId;
}


void Vehicle::setUserId(int64_t value)
{
    m_UserId = value;
    m_UserIdIsSet = true;
}
bool Vehicle::userIdIsSet() const
{
    return m_UserIdIsSet;
}

void Vehicle::unsetUserId()
{
    m_UserIdIsSet = false;
}

utility::string_t Vehicle::getName() const
{
    return m_Name;
}


void Vehicle::setName(utility::string_t value)
{
    m_Name = value;
    
}
std::vector<utility::string_t>& Vehicle::getPhotoUrls()
{
    return m_PhotoUrls;
}

void Vehicle::setPhotoUrls(std::vector<utility::string_t> value)
{
    m_PhotoUrls = value;
    
}
utility::string_t Vehicle::getVehicleType() const
{
    return m_VehicleType;
}


void Vehicle::setVehicleType(utility::string_t value)
{
    m_VehicleType = value;
    
}
}
}
}
}

