/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Fine'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Fine'));
  } else {
    // Browser globals (root is window)
    if (!root.VehicleMaintanceManager) {
      root.VehicleMaintanceManager = {};
    }
    root.VehicleMaintanceManager.FineApi = factory(root.VehicleMaintanceManager.ApiClient, root.VehicleMaintanceManager.Fine);
  }
}(this, function(ApiClient, Fine) {
  'use strict';

  /**
   * Fine service.
   * @module api/FineApi
   * @version 0.0.1
   */

  /**
   * Constructs a new FineApi. 
   * @alias module:api/FineApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addFineToVehicleId operation.
     * @callback module:api/FineApi~addFineToVehicleIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a fine to the vehicle
     * 
     * @param {Number} vehicleId ID of vehicle that needs to be updated
     * @param {Number} amount The total amount of fines
     * @param {module:api/FineApi~addFineToVehicleIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addFineToVehicleId = function(vehicleId, amount, callback) {
      var postBody = null;

      // verify the required parameter 'vehicleId' is set
      if (vehicleId === undefined || vehicleId === null) {
        throw new Error("Missing the required parameter 'vehicleId' when calling addFineToVehicleId");
      }

      // verify the required parameter 'amount' is set
      if (amount === undefined || amount === null) {
        throw new Error("Missing the required parameter 'amount' when calling addFineToVehicleId");
      }


      var pathParams = {
        'vehicleId': vehicleId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'amount': amount
      };

      var authNames = ['vehiclegarage_auth'];
      var contentTypes = ['application/x-www-form-urlencoded'];
      var accepts = ['application/xml', 'application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/fine/vehicle/{vehicleId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteFine operation.
     * @callback module:api/FineApi~deleteFineCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a fine
     * 
     * @param {Number} fineId fine id to delete
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiKey 
     * @param {module:api/FineApi~deleteFineCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteFine = function(fineId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'fineId' is set
      if (fineId === undefined || fineId === null) {
        throw new Error("Missing the required parameter 'fineId' when calling deleteFine");
      }


      var pathParams = {
        'fineId': fineId
      };
      var queryParams = {
      };
      var headerParams = {
        'api_key': opts['apiKey']
      };
      var formParams = {
      };

      var authNames = ['vehiclegarage_auth'];
      var contentTypes = [];
      var accepts = ['application/xml', 'application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/fine/{fineId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getFineById operation.
     * @callback module:api/FineApi~getFineByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Fine} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find fine by ID
     * Returns a single fine
     * @param {Number} fineId ID of fine to return
     * @param {module:api/FineApi~getFineByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Fine}
     */
    this.getFineById = function(fineId, callback) {
      var postBody = null;

      // verify the required parameter 'fineId' is set
      if (fineId === undefined || fineId === null) {
        throw new Error("Missing the required parameter 'fineId' when calling getFineById");
      }


      var pathParams = {
        'fineId': fineId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/xml', 'application/json'];
      var returnType = Fine;

      return this.apiClient.callApi(
        '/fine/{fineId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
