/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Reminder'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Reminder'));
  } else {
    // Browser globals (root is window)
    if (!root.VehicleMaintanceManager) {
      root.VehicleMaintanceManager = {};
    }
    root.VehicleMaintanceManager.ReminderApi = factory(root.VehicleMaintanceManager.ApiClient, root.VehicleMaintanceManager.Reminder);
  }
}(this, function(ApiClient, Reminder) {
  'use strict';

  /**
   * Reminder service.
   * @module api/ReminderApi
   * @version 0.0.1
   */

  /**
   * Constructs a new ReminderApi. 
   * @alias module:api/ReminderApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addReminderToVehicleId operation.
     * @callback module:api/ReminderApi~addReminderToVehicleIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a reminder to the vehicle
     * 
     * @param {Number} vehicleId ID of vehicle that needs to be updated
     * @param {String} message Reminder message
     * @param {module:api/ReminderApi~addReminderToVehicleIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addReminderToVehicleId = function(vehicleId, message, callback) {
      var postBody = null;

      // verify the required parameter 'vehicleId' is set
      if (vehicleId === undefined || vehicleId === null) {
        throw new Error("Missing the required parameter 'vehicleId' when calling addReminderToVehicleId");
      }

      // verify the required parameter 'message' is set
      if (message === undefined || message === null) {
        throw new Error("Missing the required parameter 'message' when calling addReminderToVehicleId");
      }


      var pathParams = {
        'vehicleId': vehicleId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'message': message
      };

      var authNames = ['vehiclegarage_auth'];
      var contentTypes = ['application/x-www-form-urlencoded'];
      var accepts = ['application/xml', 'application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/reminder/vehicle/{vehicleId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteReminder operation.
     * @callback module:api/ReminderApi~deleteReminderCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a reminder
     * 
     * @param {Number} reminderId reminder id to delete
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiKey 
     * @param {module:api/ReminderApi~deleteReminderCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteReminder = function(reminderId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'reminderId' is set
      if (reminderId === undefined || reminderId === null) {
        throw new Error("Missing the required parameter 'reminderId' when calling deleteReminder");
      }


      var pathParams = {
        'reminderId': reminderId
      };
      var queryParams = {
      };
      var headerParams = {
        'api_key': opts['apiKey']
      };
      var formParams = {
      };

      var authNames = ['vehiclegarage_auth'];
      var contentTypes = [];
      var accepts = ['application/xml', 'application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/reminder/{reminderId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getReminderById operation.
     * @callback module:api/ReminderApi~getReminderByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Reminder} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find reminder by ID
     * Returns a single reminder
     * @param {Number} reminderId ID of reminder to return
     * @param {module:api/ReminderApi~getReminderByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Reminder}
     */
    this.getReminderById = function(reminderId, callback) {
      var postBody = null;

      // verify the required parameter 'reminderId' is set
      if (reminderId === undefined || reminderId === null) {
        throw new Error("Missing the required parameter 'reminderId' when calling getReminderById");
      }


      var pathParams = {
        'reminderId': reminderId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/xml', 'application/json'];
      var returnType = Reminder;

      return this.apiClient.callApi(
        '/reminder/{reminderId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
