/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiResponse', 'model/Fine', 'model/Garage', 'model/Refuel', 'model/Reminder', 'model/Trip', 'model/User', 'model/Vehicle', 'api/FineApi', 'api/GarageApi', 'api/RefuelApi', 'api/ReminderApi', 'api/TripApi', 'api/UserApi', 'api/VehicleApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ApiResponse'), require('./model/Fine'), require('./model/Garage'), require('./model/Refuel'), require('./model/Reminder'), require('./model/Trip'), require('./model/User'), require('./model/Vehicle'), require('./api/FineApi'), require('./api/GarageApi'), require('./api/RefuelApi'), require('./api/ReminderApi'), require('./api/TripApi'), require('./api/UserApi'), require('./api/VehicleApi'));
  }
}(function(ApiClient, ApiResponse, Fine, Garage, Refuel, Reminder, Trip, User, Vehicle, FineApi, GarageApi, RefuelApi, ReminderApi, TripApi, UserApi, VehicleApi) {
  'use strict';

  /**
   * This_is_a_sample_vehicle_maintance_manager_server_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var VehicleMaintanceManager = require('index'); // See note below*.
   * var xxxSvc = new VehicleMaintanceManager.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new VehicleMaintanceManager.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new VehicleMaintanceManager.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new VehicleMaintanceManager.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ApiResponse model constructor.
     * @property {module:model/ApiResponse}
     */
    ApiResponse: ApiResponse,
    /**
     * The Fine model constructor.
     * @property {module:model/Fine}
     */
    Fine: Fine,
    /**
     * The Garage model constructor.
     * @property {module:model/Garage}
     */
    Garage: Garage,
    /**
     * The Refuel model constructor.
     * @property {module:model/Refuel}
     */
    Refuel: Refuel,
    /**
     * The Reminder model constructor.
     * @property {module:model/Reminder}
     */
    Reminder: Reminder,
    /**
     * The Trip model constructor.
     * @property {module:model/Trip}
     */
    Trip: Trip,
    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User: User,
    /**
     * The Vehicle model constructor.
     * @property {module:model/Vehicle}
     */
    Vehicle: Vehicle,
    /**
     * The FineApi service constructor.
     * @property {module:api/FineApi}
     */
    FineApi: FineApi,
    /**
     * The GarageApi service constructor.
     * @property {module:api/GarageApi}
     */
    GarageApi: GarageApi,
    /**
     * The RefuelApi service constructor.
     * @property {module:api/RefuelApi}
     */
    RefuelApi: RefuelApi,
    /**
     * The ReminderApi service constructor.
     * @property {module:api/ReminderApi}
     */
    ReminderApi: ReminderApi,
    /**
     * The TripApi service constructor.
     * @property {module:api/TripApi}
     */
    TripApi: TripApi,
    /**
     * The UserApi service constructor.
     * @property {module:api/UserApi}
     */
    UserApi: UserApi,
    /**
     * The VehicleApi service constructor.
     * @property {module:api/VehicleApi}
     */
    VehicleApi: VehicleApi
  };

  return exports;
}));
