=begin
#Vehicle Maintance Manager

#This is a sample vehicle maintance manager server.

OpenAPI spec version: 0.0.1
Contact: apiteam@vmmapi
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::FineApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FineApi' do
  before do
    # run before each test
    @instance = SwaggerClient::FineApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FineApi' do
    it 'should create an instance of FineApi' do
      expect(@instance).to be_instance_of(SwaggerClient::FineApi)
    end
  end

  # unit tests for add_fine_to_vehicle_id
  # Add a fine to the vehicle
  # 
  # @param vehicle_id ID of vehicle that needs to be updated
  # @param amount The total amount of fines
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_fine_to_vehicle_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_fine
  # Deletes a fine
  # 
  # @param fine_id fine id to delete
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_key 
  # @return [nil]
  describe 'delete_fine test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_fine_by_id
  # Find fine by ID
  # Returns a single fine
  # @param fine_id ID of fine to return
  # @param [Hash] opts the optional parameters
  # @return [Fine]
  describe 'get_fine_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
