=begin
#Vehicle Maintance Manager

#This is a sample vehicle maintance manager server.

OpenAPI spec version: 0.0.1
Contact: apiteam@vmmapi
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::GarageApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GarageApi' do
  before do
    # run before each test
    @instance = SwaggerClient::GarageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GarageApi' do
    it 'should create an instance of GarageApi' do
      expect(@instance).to be_instance_of(SwaggerClient::GarageApi)
    end
  end

  # unit tests for garage_inventory_get
  # Get all registered vehicles
  # 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'garage_inventory_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
