=begin
#Vehicle Maintance Manager

#This is a sample vehicle maintance manager server.

OpenAPI spec version: 0.0.1
Contact: apiteam@vmmapi
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::RefuelApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RefuelApi' do
  before do
    # run before each test
    @instance = SwaggerClient::RefuelApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RefuelApi' do
    it 'should create an instance of RefuelApi' do
      expect(@instance).to be_instance_of(SwaggerClient::RefuelApi)
    end
  end

  # unit tests for add_refuel_to_vehicle_id
  # Add a refuel bill to the vehicle
  # 
  # @param vehicle_id ID of vehicle that needs to be updated
  # @param quantity Fuel Quantity
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_refuel_to_vehicle_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_refuel
  # Deletes a refuel bill
  # 
  # @param refuel_id refuel id to delete
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_key 
  # @return [nil]
  describe 'delete_refuel test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_refuel_by_id
  # Find refuel bill by ID
  # Returns a single refuel bill
  # @param refuel_id ID of refuel to return
  # @param [Hash] opts the optional parameters
  # @return [Refuel]
  describe 'get_refuel_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
