=begin
#Vehicle Maintance Manager

#This is a sample vehicle maintance manager server.

OpenAPI spec version: 0.0.1
Contact: apiteam@vmmapi
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ReminderApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReminderApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ReminderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReminderApi' do
    it 'should create an instance of ReminderApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ReminderApi)
    end
  end

  # unit tests for add_reminder_to_vehicle_id
  # Add a reminder to the vehicle
  # 
  # @param vehicle_id ID of vehicle that needs to be updated
  # @param message Reminder message
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_reminder_to_vehicle_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_reminder
  # Deletes a reminder
  # 
  # @param reminder_id reminder id to delete
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_key 
  # @return [nil]
  describe 'delete_reminder test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_reminder_by_id
  # Find reminder by ID
  # Returns a single reminder
  # @param reminder_id ID of reminder to return
  # @param [Hash] opts the optional parameters
  # @return [Reminder]
  describe 'get_reminder_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
