=begin
#Vehicle Maintance Manager

#This is a sample vehicle maintance manager server.

OpenAPI spec version: 0.0.1
Contact: apiteam@vmmapi
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TripApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TripApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TripApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TripApi' do
    it 'should create an instance of TripApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TripApi)
    end
  end

  # unit tests for add_trip_to_vehicle_id
  # Add a trip log to the vehicle
  # 
  # @param vehicle_id ID of vehicle that needs to be updated
  # @param quantity Fuel Quantity
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_trip_to_vehicle_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_trip
  # Deletes a trip log
  # 
  # @param trip_id trip id to delete
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_key 
  # @return [nil]
  describe 'delete_trip test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_trip_by_id
  # Find trip by ID
  # Returns a single trip log
  # @param trip_id ID of trip to return
  # @param [Hash] opts the optional parameters
  # @return [Trip]
  describe 'get_trip_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
