/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VehicleMaintanceManager);
  }
}(this, function(expect, VehicleMaintanceManager) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VehicleMaintanceManager.RefuelApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RefuelApi', function() {
    describe('addRefuelToVehicleId', function() {
      it('should call addRefuelToVehicleId successfully', function(done) {
        //uncomment below and update the code to test addRefuelToVehicleId
        //instance.addRefuelToVehicleId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRefuel', function() {
      it('should call deleteRefuel successfully', function(done) {
        //uncomment below and update the code to test deleteRefuel
        //instance.deleteRefuel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRefuelById', function() {
      it('should call getRefuelById successfully', function(done) {
        //uncomment below and update the code to test getRefuelById
        //instance.getRefuelById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
