/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VehicleMaintanceManager);
  }
}(this, function(expect, VehicleMaintanceManager) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VehicleMaintanceManager.ReminderApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReminderApi', function() {
    describe('addReminderToVehicleId', function() {
      it('should call addReminderToVehicleId successfully', function(done) {
        //uncomment below and update the code to test addReminderToVehicleId
        //instance.addReminderToVehicleId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteReminder', function() {
      it('should call deleteReminder successfully', function(done) {
        //uncomment below and update the code to test deleteReminder
        //instance.deleteReminder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReminderById', function() {
      it('should call getReminderById successfully', function(done) {
        //uncomment below and update the code to test getReminderById
        //instance.getReminderById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
