/**
 * Vehicle Maintance Manager
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VehicleMaintanceManager);
  }
}(this, function(expect, VehicleMaintanceManager) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VehicleMaintanceManager.VehicleApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VehicleApi', function() {
    describe('addVehicle', function() {
      it('should call addVehicle successfully', function(done) {
        //uncomment below and update the code to test addVehicle
        //instance.addVehicle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVehicle', function() {
      it('should call deleteVehicle successfully', function(done) {
        //uncomment below and update the code to test deleteVehicle
        //instance.deleteVehicle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVehicleById', function() {
      it('should call getVehicleById successfully', function(done) {
        //uncomment below and update the code to test getVehicleById
        //instance.getVehicleById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateVehicle', function() {
      it('should call updateVehicle successfully', function(done) {
        //uncomment below and update the code to test updateVehicle
        //instance.updateVehicle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateVehicleWithForm', function() {
      it('should call updateVehicleWithForm successfully', function(done) {
        //uncomment below and update the code to test updateVehicleWithForm
        //instance.updateVehicleWithForm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadFile', function() {
      it('should call uploadFile successfully', function(done) {
        //uncomment below and update the code to test uploadFile
        //instance.uploadFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
