=begin
#Vehicle Maintance Manager

#This is a sample vehicle maintance manager server.

OpenAPI spec version: 0.0.1
Contact: apiteam@vmmapi
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/api_response'
require 'swagger_client/models/fine'
require 'swagger_client/models/garage'
require 'swagger_client/models/refuel'
require 'swagger_client/models/reminder'
require 'swagger_client/models/trip'
require 'swagger_client/models/user'
require 'swagger_client/models/vehicle'

# APIs
require 'swagger_client/api/fine_api'
require 'swagger_client/api/garage_api'
require 'swagger_client/api/refuel_api'
require 'swagger_client/api/reminder_api'
require 'swagger_client/api/trip_api'
require 'swagger_client/api/user_api'
require 'swagger_client/api/vehicle_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
