/* 
 * Vehicle Maintance Manager
 *
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Fine struct {

	Id int64 `json:"id,omitempty"`

	VehicleId int64 `json:"vehicleId"`

	Name string `json:"name"`

	Description string `json:"description"`
}
