/* 
 * Vehicle Maintance Manager
 *
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ModelApiResponse struct {

	Code int32 `json:"code,omitempty"`

	Type_ string `json:"type,omitempty"`

	Message string `json:"message,omitempty"`
}
