/* 
 * Vehicle Maintance Manager
 *
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Trip struct {

	Id int64 `json:"id,omitempty"`

	VehicleId int64 `json:"vehicleId"`

	// Traveled Distance
	Distance float32 `json:"distance"`
}
