/* 
 * Vehicle Maintance Manager
 *
 * This is a sample vehicle maintance manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@vmmapi
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Vehicle struct {

	Id int64 `json:"id,omitempty"`

	UserId int64 `json:"userId,omitempty"`

	Name string `json:"name"`

	PhotoUrls []string `json:"photoUrls"`

	// Type of vehicle
	VehicleType string `json:"vehicleType"`
}
